[package]
name = "webtingle"
version = "0.1.0"
authors = ["A. Bram Neijt <bram@neijt.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-files = "0"
actix-rt = "1"
serde = "1"